
  [storage]
  driver = "overlay"
  runroot = "/mnt/c/Users/julia/source/repos/Julian52575/puniemu-globuland/.containers/run"
  graphroot = "/mnt/c/Users/julia/source/repos/Julian52575/puniemu-globuland/.containers/storage"
  [storage.options]
  mount_program = "/nix/store/4i19nk1w31wr6fnwy2crzvyxdjzsmm25-fuse-overlayfs-1.13/bin/fuse-overlayfs"

