using Newtonsoft.Json;
using Puniemu.Src.Server.GameServer.DataClasses;
using Puniemu.Src.TableParser.DataClasses;
using Puniemu.Src.TableParser.Logic;
using System;

//// credit : Flamer12344

namespace Puniemu.Src.Server.GameServer.Logic
{
    public class MoneyExpManager
    {
        /*
        PCHIP-generated coefficients, must be regenerated if the input scores change
        The data is generated by the actual game, if you want to modify it, you can
        */

        public static void GiveYoukaiExp(
                UserYoukaiResultListRes result,
                YwpUserYoukai youkai,
                long youkaiId,
                int expToAdd,
                YwpMstYoukai MasterYoukai)
        {
            var YoukaiLevelMstTable = new TableParser<YwpMstYoukaiLevel>(DataManager.Logic.DataManager.GameDataManager.GetTableStringFromJson("ywp_mst_youkai_level"));
            var YoukaiLevelOpenMstTable = new TableParser<YwpMstYoukaiLevelOpen>(DataManager.Logic.DataManager.GameDataManager.GetTableStringFromJson("ywp_mst_youkai_level_open"));

            result.Before.Level = youkai.Level;
            result.Before.Exp = (int)youkai.Exp;
            result.Before.ExpBar.Denominator = youkai.ExpDenominator;
            result.Before.ExpBar.Numerator = youkai.ExpNumerator;
            result.Before.ExpBar.Percentage = youkai.Percentage;

            result.After.Level = result.Before.Level;
            result.After.Exp = result.Before.Exp;
            result.After.ExpBar.Denominator = result.Before.ExpBar.Denominator;
            result.After.ExpBar.Numerator = result.Before.ExpBar.Numerator;
            result.After.ExpBar.Percentage = result.Before.ExpBar.Percentage;

            if (youkai.Level < MasterYoukai.MaxLevel &&
                youkai.IsLockedLevel == 0)
            {
                int levelIndex = 0;
                int level = result.Before.Level;

                result.After.Exp = result.Before.Exp + expToAdd;

                while (levelIndex != -1)
                {
                    if (level >= MasterYoukai.MaxLevel)
                    {
                        result.After.Level = MasterYoukai.MaxLevel;
                        result.After.ExpBar.Denominator = 0;
                        result.After.ExpBar.Numerator = 0;
                        result.After.ExpBar.Percentage = 0;
                        break;
                    }
                    levelIndex = MstYoukaiManager.GetYoukaiLevelIndex(
                        YoukaiLevelMstTable,
                        MasterYoukai.LevelType,
                        level);

                    if (levelIndex == -1)
                    {
                        break;
                    }

                    level++;

                    var levelInfo = YoukaiLevelMstTable.Items[levelIndex];

                    if (result.After.Exp < levelInfo.BaseExp ||
                        result.After.Exp > levelInfo.MaxExp)
                    {
                        continue;
                    }

                    result.After.Level = levelInfo.Level;
                    result.After.ExpBar.Denominator =
                        (levelInfo.MaxExp + 1) - levelInfo.BaseExp;
                    result.After.ExpBar.Numerator =
                        result.After.Exp - levelInfo.BaseExp;
                    result.After.ExpBar.Percentage =
                        (int)(((double)result.After.ExpBar.Numerator /
                               result.After.ExpBar.Denominator) * 100.0);

                    break;
                }

                int levelOpenIndex = MstYoukaiManager.GetYoukaiLevelOpenIndex(
                    YoukaiLevelOpenMstTable,
                    result.Before.Level,
                    result.After.Level,
                    MasterYoukai.YoukaiRarity);

                if (levelOpenIndex != -1 && result.After.Level < MasterYoukai.MaxLevel)
                {
                    result.After.Level =
                        YoukaiLevelOpenMstTable.Items[levelOpenIndex].Level;

                    youkai.IsLockedLevel = 1;

                    int tmpIndex = MstYoukaiManager.GetYoukaiLevelIndex(
                        YoukaiLevelMstTable,
                        MasterYoukai.LevelType,
                        result.After.Level);

                    if (tmpIndex != -1)
                    {
                        var levelInfo = YoukaiLevelMstTable.Items[tmpIndex];

                        result.After.ExpBar.Denominator =
                            (levelInfo.MaxExp + 1) - levelInfo.BaseExp;

                        result.After.Exp = levelInfo.BaseExp;
                        result.After.ExpBar.Numerator = 0;
                        result.After.ExpBar.Percentage = 0;
                    }
                }
            }

            youkai.Level = result.After.Level;
            youkai.Exp = result.After.Exp;
            youkai.ExpDenominator = result.After.ExpBar.Denominator;
            youkai.ExpNumerator = result.After.ExpBar.Numerator;
            youkai.Percentage = result.After.ExpBar.Percentage;

            int hpOffset =
                (MasterYoukai.MaxHp -
                 MasterYoukai.BaseHp)
                / MasterYoukai.MaxLevel;

            int atkOffset =
                (MasterYoukai.MaxAtk -
                 MasterYoukai.BaseAtk)
                / MasterYoukai.MaxLevel;

            youkai.Hp += hpOffset * (result.After.Level - result.Before.Level);
            youkai.Atk += atkOffset * (result.After.Level - result.Before.Level);

            if (youkai.IsLockedLevel == 1)
                result.IsLockLevel = true;

            if (youkai.Level >= MasterYoukai.MaxLevel)
            {
                result.IsMaxLevel = true;
                result.IsLockLevel = false;

                youkai.IsLockedLevel = 0;
                youkai.Level = MasterYoukai.MaxLevel;
            }
        }


        public static int ScoreToMoney(int score)
        {
            if (score >= 0 && score <= 19503)
            {
                double t = score - 0;
                return (int)Math.Round(
                    -9.31378239683659486e-13 * t * t * t
                  + 9.49718454859748785e-09 * t * t
                  + 1.65599269055426764e-03 * t
                  + 0.0
                );
            }
            else if (score >= 19503 && score <= 98886)
            {
                double t = score - 19503;
                return (int)Math.Round(
                    3.54735885620046944e-14 * t * t * t
                  + -7.02074683060136725e-09 * t * t
                  + 9.63643205228385206e-04 * t
                  + 29.0
                );
            }
            else if (score >= 98886 && score <= 730551)
            {
                double t = score - 98886;
                return (int)Math.Round(
                    4.13930576528173492e-17 * t * t * t
                  + -2.14673863641769430e-10 * t * t
                  + 5.19614869537963608e-04 * t
                  + 79.0
                );
            }
            else if (score >= 730551 && score <= 4693781)
            {
                double t = score - 730551;
                return (int)Math.Round(
                    2.26140561025886510e-18 * t * t * t
                  + -3.11738313337231444e-11 * t * t
                  + 2.97958510870173878e-04 * t
                  + 332.0
                );
            }
            else if (score >= 4693781 && score <= 16342265)
            {
                double t = score - 4693781;
                return (int)Math.Round(
                    1.13702467628649215e-19 * t * t * t
                  + -4.81573027415106134e-12 * t * t
                  + 1.57421380310510930e-04 * t
                  + 1164.0
                );
            }
            else if (score >= 16342265 && score <= 43639866)
            {
                double t = score - 16342265;
                return (int)Math.Round(
                    9.70709432301333797e-21 * t * t * t
                  + -1.00454788996105275e-12 * t * t
                  + 9.15133676205519498e-05 * t
                  + 2524.0
                );
            }
            else if (score >= 43639866 && score <= 87258813)
            {
                double t = score - 43639866;
                return (int)Math.Round(
                    1.49992019413226535e-21 * t * t * t
                  + -2.99330578210795985e-13 * t * t
                  + 5.83698593381509477e-05 * t
                  + 4471.0
                );
            }
            else if (score >= 87258813 && score <= 164548262)
            {
                double t = score - 87258813;
                return (int)Math.Round(
                    1.50583294243071944e-22 * t * t * t
                  + -9.36343915347345514e-14 * t * t
                  + 4.08181909845549339e-05 * t
                  + 6572.0
                );
            }
            else if (score >= 164548262 && score <= 341173912)
            {
                double t = score - 164548262;
                return (int)Math.Round(
                    4.22870018286688518e-23 * t * t * t
                  + -3.54437707789627279e-14 * t * t
                  + 2.90428896458268666e-05 * t
                  + 9237.0
                );
            }
            else if (score >= 341173912 && score <= 501126231)
            {
                double t = score - 341173912;
                return (int)Math.Round(
                    1.25822833054158318e-23 * t * t * t
                  + -1.82651444054791573e-14 * t * t
                  + 2.04799661524042164e-05 * t
                  + 13494.0
                );
            }
            else if (score >= 501126231 && score <= 1000021478)
            {
                double t = score - 501126231;
                return (int)Math.Round(
                    1.69062812767858107e-24 * t * t * t
                  + -5.61677884535533050e-15 * t * t
                  + 1.56026052486079671e-05 * t
                  + 16354.0
                );
            }
            else if (score >= 1000021478 && score <= 1501115792)
            {
                double t = score - 1000021478;
                return (int)Math.Round(
                    1.98692409103500659e-24 * t * t * t
                  + -3.90141531575173342e-15 * t * t
                  + 1.12606108162125956e-05 * t
                  + 22950.0
                );
            }
            else if (score >= 1501115792 && score <= 2000028972)
            {
                double t = score - 1501115792;
                return (int)Math.Round(
                    1.22922693348241123e-24 * t * t * t
                  + -2.18841543736151449e-15 * t * t
                  + 8.84737991664937757e-06 * t
                  + 27863.0
                );
            }
            else if (score >= 2000028972 && score <= 2147393648)
            {
                double t = score - 2000028972;
                return (int)Math.Round(
                    5.63928751381472842e-24 * t * t * t
                  + -2.86938696083429261e-15 * t * t
                  + 7.58163801728976713e-06 * t
                  + 31885.0
                );
            }
            return 1000;
        }
        
        
        public static int ScoreToExp(int score)
        {
            if (score >= 0 && score <= 19503)
            {
                double t = score - 0;
                return (int)Math.Round(
                    -4.48361255856927931e-12 * t * t * t
                  + 4.54072418115759809e-08 * t * t
                  + 8.10077200016582656e-03 * t
                  + 0.0
                );
            }
            else if (score >= 19503 && score <= 98886)
            {
                double t = score - 19503;
                return (int)Math.Round(
                    1.73097170552723314e-13 * t * t * t
                  + -3.42942070042694355e-08 * t * t
                  + 4.75567197901465705e-03 * t
                  + 142.0
                );
            }
            else if (score >= 98886 && score <= 730551)
            {
                double t = score - 98886;
                return (int)Math.Round(
                    1.95776881784349619e-16 * t * t * t
                  + -1.05296412884479166e-09 * t * t
                  + 2.58331681492249060e-03 * t
                  + 390.0
                );
            }
            else if (score >= 730551 && score <= 4693781)
            {
                double t = score - 730551;
                return (int)Math.Round(
                    1.11372057468599232e-17 * t * t * t
                  + -1.54661378642014054e-10 * t * t
                  + 1.48742096434320960e-03 * t
                  + 1651.0
                );
            }
            else if (score >= 4693781 && score <= 16342265)
            {
                double t = score - 4693781;
                return (int)Math.Round(
                    5.71990593904137891e-19 * t * t * t
                  + -2.41315168916343234e-11 * t * t
                  + 7.86306421119969479e-04 * t
                  + 5810.0
                );
            }
            else if (score >= 16342265 && score <= 43639866)
            {
                double t = score - 16342265;
                return (int)Math.Round(
                    4.83447957840900533e-20 * t * t * t
                  + -5.00972216520284317e-12 * t * t
                  + 4.56950615463259588e-04 * t
                  + 12599.0
                );
            }
            else if (score >= 43639866 && score <= 87258813)
            {
                double t = score - 43639866;
                return (int)Math.Round(
                    7.47985780985637522e-21 * t * t * t
                  + -1.49449221111500470e-12 * t * t
                  + 2.91517503887367467e-04 * t
                  + 22323.0
                );
            }
            else if (score >= 87258813 && score <= 164548262)
            {
                double t = score - 87258813;
                return (int)Math.Round(
                    7.18498919412637178e-22 * t * t * t
                  + -4.65212972571956305e-13 * t * t
                  + 2.03834964531046138e-04 * t
                  + 32816.0
                );
            }
            else if (score >= 164548262 && score <= 341173912)
            {
                double t = score - 164548262;
                return (int)Math.Round(
                    2.30957298582560380e-22 * t * t * t
                  + -1.81200109349690174e-13 * t * t
                  + 1.44799058346940568e-04 * t
                  + 46123.0
                );
            }
            else if (score >= 341173912 && score <= 501126231)
            {
                double t = score - 341173912;
                return (int)Math.Round(
                    4.39818175640677205e-23 * t * t * t
                  + -8.65722555443258087e-14 * t * t
                  + 1.02405145564190197e-04 * t
                  + 67318.0
                );
            }
            else if (score >= 501126231 && score <= 1000021478)
            {
                double t = score - 501126231;
                return (int)Math.Round(
                    9.18133825116994149e-24 * t * t * t
                  + -2.87743979698713797e-14 * t * t
                  + 7.80860701691730682e-05 * t
                  + 81663.0
                );
            }
            else if (score >= 1000021478 && score <= 1501115792)
            {
                double t = score - 1000021478;
                return (int)Math.Round(
                    -2.34707446800188890e-23 * t * t * t
                  + -2.74323642551017038e-15 * t * t
                  + 5.62308573766058303e-05 * t
                  + 114598.0
                );
            }
            else if (score >= 1501115792 && score <= 2000028972)
            {
                double t = score - 1501115792;
                return (int)Math.Round(
                    9.83129676638006056e-23 * t * t * t
                  + -6.42347810719374237e-14 * t * t
                  + 3.58014211032697520e-05 * t
                  + 139133.0
                );
            }
            else if (score >= 2000028972 && score <= 2147393648)
            {
                double t = score - 2000028972;
                return (int)Math.Round(
                    -9.59690854169443042e-22 * t * t * t
                  + 3.58486312713437551e-13 * t * t
                  + 4.51207919454216030e-05 * t
                  + 153215.0
                );
            }
            return 10000;
        }
    }
}
